# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = false

# Fabric / Minecraft
minecraft_version = 1.21.11
loader_version = 0.18.4
loom_version = 1.15.5
fabric_api_version = 0.141.3+1.21.11

# Mod
mod_id = create_enchantment_industry
mod_artifact_id = create-enchantment-industry-fly
mod_name = Create: Enchantment Industry Fly
mod_license = LGPL-3.0-or-later
mod_version = 2.5.1-p.1
mod_release_channel = ALPHA
mod_group_id = plus.dragons.createenchantmentindustry
mod_authors = DragonsPlus
mod_description = Enchantment, Experience, Enhancement and Enlightening - with Create Fly
mod_github = https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fly

# Required dependencies
create_fly_version = 1.21.11-6.0.9-5
create_version_range = >=6.0.9-5 <6.1.0
create_dragons_plus_version = 1.11.4-p2
jei_version = 27.4.0.15

# Tests
junit_version = 5.12.2
